# Generated by Django 5.0.2 on 2024-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_category_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("channel_id", models.CharField(max_length=64)),
                ("channel_url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
